/* nortec/js/jobs.js — job data with Nortec scoring */

export const JOBS = [
  {
    id: 'j001',
    company: 'Praxent',
    title: 'Senior Software Engineer (React & Node.js)',
    location: 'Remote · LatAm',
    type: 'Full-time',
    salary: 'USD Competitive',
    salaryEstimate: '$75K–$95K USD',
    salarySource: 'nortec-estimate',
    salaryNum: null,
    tags: ['React', 'Node.js', 'Agile', 'REST APIs'],
    function: 'Engineering',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'US CT/ET overlap',
    aiRelevance: false,
    link: 'https://job-boards.greenhouse.io/praxent/jobs/7589205003',
    source: 'Greenhouse',
    sourceDate: '2026-05-09',
    score: 4,
    scoreBreakdown: {
      latamEligibility: 5,
      salaryTransparency: 2,
      remoteQuality: 5,
      careerUpside: 4,
      aiRelevance: 2,
      applicationClarity: 4,
    },
    why: 'Strong fullstack role open explicitly to LatAm. Agile environment, mentorship path, and direct client exposure. Salary not listed but company is well-known for fair USD rates.',
    whyEs: 'Rol fullstack sólido abierto explícitamente para LatAm. Entorno ágil, ruta de mentoría y exposición directa con clientes. No publican salario, pero la empresa es conocida por manejar tarifas justas en USD.',
    applyAngle: 'Highlight sprint delivery experience, fullstack breadth (UI + APIs + cloud), and direct client communication.',
    applyAngleEs: 'Destaca tu experiencia entregando sprints, amplitud fullstack (UI + APIs + nube) y comunicación directa con clientes.',
  },
  {
    id: 'j002',
    company: 'Luxury Presence',
    title: 'Staff Software Engineer — Data Platform & AI',
    location: 'Remote · LatAm',
    type: 'Full-time',
    salary: 'Senior USD',
    salaryEstimate: '$130K–$160K USD',
    salarySource: 'nortec-estimate',
    salaryNum: null,
    tags: ['Python', 'AWS', 'LLMs', 'Data Pipelines', 'PostgreSQL'],
    function: 'Engineering',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'Flexible',
    aiRelevance: true,
    link: 'https://jobs.lever.co/luxurypresence/88e79420-0e50-413b-85c1-58ded03087cd',
    source: 'Lever',
    sourceDate: '2026-03-29',
    score: 5,
    scoreBreakdown: {
      latamEligibility: 5,
      salaryTransparency: 3,
      remoteQuality: 5,
      careerUpside: 5,
      aiRelevance: 5,
      applicationClarity: 5,
    },
    why: 'Sits at the intersection of backend engineering, data infra, and applied AI. MLS data pipelines + LLM agents. Staff-level = career-defining for LatAm engineers.',
    whyEs: 'Está en la intersección de backend, infraestructura de datos e IA aplicada. Pipelines de datos MLS + agentes con LLM. Nivel Staff = una oportunidad que puede definir la carrera de ingenieros en LatAm.',
    applyAngle: 'Show production AI/ML experience (not just prompt engineering), data pipeline work at scale, and observability.',
    applyAngleEs: 'Muestra experiencia real de IA/ML en producción (no solo prompt engineering), trabajo con pipelines de datos a escala y observabilidad.',
  },
  {
    id: 'j003',
    company: 'Clara',
    title: 'Forward-Deployed AI Engineer',
    location: 'Remote · LatAm / São Paulo',
    type: 'Full-time',
    salary: 'USD Competitive',
    salaryEstimate: '$90K–$120K USD',
    salarySource: 'nortec-estimate',
    salaryNum: null,
    tags: ['LLMs', 'Anthropic API', 'Docker', 'PostgreSQL', 'AWS'],
    function: 'Engineering',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'Americas',
    aiRelevance: true,
    link: 'https://job-boards.greenhouse.io/clara/jobs/5095342007',
    source: 'Greenhouse',
    sourceDate: '2026-04-01',
    score: 5,
    scoreBreakdown: {
      latamEligibility: 5,
      salaryTransparency: 3,
      remoteQuality: 5,
      careerUpside: 5,
      aiRelevance: 5,
      applicationClarity: 5,
    },
    why: 'Clara is LatAm-born fintech (backed by Coatue, General Catalyst, Goldman). AI innovation team, ultra-fast shipping culture. Perfect for engineers with 2+ AI features in prod.',
    whyEs: 'Clara es una fintech nacida en LatAm (respaldada por Coatue, General Catalyst y Goldman). Equipo de innovación en IA con cultura de envío ultrarrápido. Ideal para ingenieros con 2+ funcionalidades de IA en producción.',
    applyAngle: 'Show real LLM integrations you shipped to production. Clara wants builders, not AI theorists.',
    applyAngleEs: 'Muestra integraciones reales de LLM que hayas llevado a producción. Clara busca builders, no teóricos de IA.',
  },
  {
    id: 'j004',
    company: 'Rapptr Labs',
    title: 'QA Analyst — iOS & Android Mobile',
    location: 'Remote · LatAm (ET hours)',
    type: 'Full-time',
    salary: 'Disclosed on application',
    salaryEstimate: '$35K–$50K USD',
    salarySource: 'nortec-estimate',
    salaryNum: null,
    tags: ['iOS', 'Android', 'Manual Testing', 'Agile', 'ET overlap'],
    function: 'QA',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'ET (10am–3pm EST core)',
    aiRelevance: false,
    link: 'https://www.glassdoor.com/Job/remote-qa-latam-jobs-SRCH_IL.0,6_IS11047_KO7,15.htm',
    source: 'Glassdoor',
    sourceDate: '2026-05-01',
    score: 3,
    scoreBreakdown: {
      latamEligibility: 5,
      salaryTransparency: 1,
      remoteQuality: 4,
      careerUpside: 3,
      aiRelevance: 1,
      applicationClarity: 4,
    },
    why: 'Solid entry/mid QA role, good for LatAm with ET morning overlap. No salary listed — ask early in the process.',
    whyEs: 'Rol QA sólido de nivel entry/mid, bueno para LatAm con solape en la mañana ET. No publican salario — pregúntalo temprano en el proceso.',
    applyAngle: 'Emphasize detailed test case writing, bug reproduction clarity, and cross-platform mobile experience.',
    applyAngleEs: 'Enfatiza redacción detallada de casos de prueba, claridad al reproducir bugs y experiencia mobile multiplataforma.',
  },
  {
    id: 'j005',
    company: 'Whippy',
    title: 'Customer Success Manager',
    location: 'Remote · LatAm',
    type: 'Full-time',
    salary: '~$35,000 USD/yr',
    salaryEstimate: '$32K–$38K USD',
    salarySource: 'listed',
    salaryNum: 35000,
    tags: ['Customer Success', 'AI Comms', 'English required', 'SaaS'],
    function: 'Customer Success',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'US overlap',
    aiRelevance: true,
    link: 'https://www.ziprecruiter.com/Jobs/Remote-Latam-Developer',
    source: 'ZipRecruiter',
    sourceDate: '2026-05-06',
    score: 4,
    scoreBreakdown: {
      latamEligibility: 5,
      salaryTransparency: 5,
      remoteQuality: 5,
      careerUpside: 3,
      aiRelevance: 3,
      applicationClarity: 4,
    },
    why: 'Salary listed — rare and honest. Fast-growing AI comms platform. CS role at an AI company = exposure to AI-native product workflows.',
    whyEs: 'Salario publicado — raro y transparente. Plataforma de comunicación con IA en rápido crecimiento. Un rol de CS en una empresa de IA te da exposición a flujos de producto nativos en IA.',
    applyAngle: 'Show onboarding experience, retention metrics you\'ve influenced, and comfort with async US client communication.',
    applyAngleEs: 'Muestra experiencia en onboarding, métricas de retención que hayas impactado y comodidad con comunicación asíncrona con clientes de EE.UU.',
  },
  {
    id: 'j006',
    company: 'Luxury Presence',
    title: 'Staff Frontend Engineer',
    location: 'Remote · LatAm',
    type: 'Full-time',
    salary: 'Competitive USD',
    salaryEstimate: '$120K–$150K USD',
    salarySource: 'nortec-estimate',
    tags: ['React', 'TypeScript', 'AI', 'Frontend'],
    function: 'Engineering',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'Flexible',
    aiRelevance: true,
    link: 'https://jobs.lever.co/luxurypresence/e7a3a0f8-80cf-4a7b-a49b-4ee2f37a3d31',
    source: 'Lever',
    sourceDate: '2026-04-07',
    score: 5,
    why: 'Luxury Presence is in the top 1% of companies applying AI to their products — and they build with it daily using Anthropic tokens at scale. This is a frontend role inside a genuinely AI-native engineering org.',
    whyEs: 'Luxury Presence está en el top 1% de empresas que aplican IA a sus productos — y construyen con ella a diario. Este rol de frontend es dentro de una organización de ingeniería verdaderamente AI-native.',
    applyAngle: 'Show AI-assisted development experience — Cursor, Copilot, Claude. They literally give engineers unlimited Anthropic tokens. Demonstrate React at scale and system design thinking.',
    applyAngleEs: 'Muestra experiencia con desarrollo asistido por IA — Cursor, Copilot, Claude. Demuestratra React a escala y pensamiento de diseño de sistemas.',
  },
  {
    id: 'j007',
    company: 'Luxury Presence',
    title: 'Staff Software Engineer — AI Marketing',
    location: 'Remote · LatAm',
    type: 'Full-time',
    salary: 'Competitive USD',
    salaryEstimate: '$130K–$160K USD',
    salarySource: 'nortec-estimate',
    tags: ['Python', 'LLMs', 'AWS', 'AI Marketing'],
    function: 'Engineering',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'Flexible',
    aiRelevance: true,
    link: 'https://jobs.lever.co/luxurypresence/1a239c88-5384-4b9b-b751-11593b22094d',
    source: 'Lever',
    sourceDate: '2026-04-07',
    score: 5,
    why: 'A staff-level AI engineering role at a Series C company heading to $100M ARR. You shape platform architecture and drive AI-powered product delivery. Rare combination of scale, AI focus, and LatAm eligibility.',
    whyEs: 'Rol de ingeniería AI a nivel staff en una empresa Serie C rumbo a $100M ARR. Das forma a la arquitectura de plataforma y lideras la entrega de productos impulsados por IA.',
    applyAngle: 'Lead with production AI systems you have shipped. Show architecture decisions, not just code. Luxury Presence wants engineers who think about how AI changes system design.',
    applyAngleEs: 'Lidera con sistemas de IA en producción que hayas lanzado. Muestra decisiones de arquitectura, no solo código.',
  },
  {
    id: 'j008',
    company: 'Bluelight Consulting',
    title: 'React Engineer',
    location: 'Remote · LatAm',
    type: 'Full-time',
    salary: 'Competitive USD',
    salaryEstimate: '$60K–$90K USD',
    salarySource: 'nortec-estimate',
    tags: ['React', 'JavaScript', 'SaaS', 'Frontend'],
    function: 'Engineering',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'US overlap',
    aiRelevance: false,
    link: 'https://jobs.lever.co/bluelightconsulting/198322a8-f5ec-4285-b8df-b056e5434d17',
    source: 'Lever',
    sourceDate: '2026-01-04',
    score: 4,
    why: 'Bluelight is a US consultancy that hires exclusively across LatAm and Central/South America. Stable client work, strong engineering culture, and real career growth for mid-senior React engineers.',
    whyEs: 'Bluelight es una consultora estadounidense que contrata exclusivamente en LatAm. Trabajo estable con clientes, cultura de ingeniería sólida y crecimiento real para ingenieros React.',
    applyAngle: 'Emphasize component architecture, performance optimization, and experience working in client-facing SaaS products. Show your ability to collaborate async with US-based teams.',
    applyAngleEs: 'Enfatiza arquitectura de componentes, optimización de rendimiento y experiencia en productos SaaS. Muestra tu capacidad de colaborar de forma asíncrona con equipos en EE.UU.',
  },
  {
    id: 'j009',
    company: 'Bluelight Consulting',
    title: 'Data Engineer',
    location: 'Remote · LatAm',
    type: 'Full-time',
    salary: 'Competitive USD',
    salaryEstimate: '$65K–$95K USD',
    salarySource: 'nortec-estimate',
    tags: ['AWS', 'Python', 'SQL', 'Data Pipelines', 'Linux'],
    function: 'Data & AI',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'US overlap',
    aiRelevance: false,
    link: 'https://jobs.lever.co/bluelightconsulting/ba92487f-ae0b-4115-b591-6d0b87afbed6',
    source: 'Lever',
    sourceDate: '2026-01-15',
    score: 4,
    why: 'Bluelight hires data engineers across LatAm for US client projects. AWS/Linux cloud work, data integration pipelines, and direct client impact. Good for engineers wanting variety across multiple projects.',
    whyEs: 'Bluelight contrata ingenieros de datos en LatAm para proyectos con clientes en EE.UU. Trabajo en AWS/Linux, pipelines de integración de datos e impacto directo en clientes.',
    applyAngle: 'Show AWS data pipeline experience, unit/integration testing discipline, and ability to write documentation. Bluelight values engineers who make their work visible and maintainable.',
    applyAngleEs: 'Muestra experiencia con pipelines de datos en AWS, disciplina de testing y capacidad de documentar. Bluelight valora ingenieros que hacen su trabajo visible y mantenible.',
  },
  {
    id: 'j010',
    company: 'Bluelight Consulting',
    title: 'DataOps / ML Engineer',
    location: 'Remote · LatAm',
    type: 'Full-time',
    salary: 'Competitive USD',
    salaryEstimate: '$75K–$105K USD',
    salarySource: 'nortec-estimate',
    tags: ['MLOps', 'Python', 'AWS', 'Data Pipelines', 'ML'],
    function: 'Data & AI',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'US overlap',
    aiRelevance: true,
    link: 'https://jobs.lever.co/bluelightconsulting/1bb4a2a9-7e2e-4e1d-bc7d-d5b0e8bac39d',
    source: 'Lever',
    sourceDate: '2025-12-13',
    score: 4,
    why: 'MLOps roles are among the fastest growing in LatAm remote hiring. This one sits at the intersection of data engineering and ML — high value, high demand, and explicitly open to LatAm.',
    whyEs: 'Los roles de MLOps están entre los de mayor crecimiento en contratación remota en LatAm. Este rol está en la intersección de ingeniería de datos y ML — alto valor, alta demanda.',
    applyAngle: 'Show end-to-end ML pipeline experience — from data ingestion to model deployment. Monitoring and retraining workflows are a strong differentiator here.',
    applyAngleEs: 'Muestra experiencia en pipelines de ML de extremo a extremo — desde ingesta de datos hasta despliegue de modelos. Los flujos de monitoreo y reentrenamiento son un diferenciador clave.',
  },
  {
    id: 'j011',
    company: 'Bluelight Consulting',
    title: 'DevOps Engineer',
    location: 'Remote · LatAm',
    type: 'Full-time',
    salary: 'Competitive USD',
    salaryEstimate: '$70K–$100K USD',
    salarySource: 'nortec-estimate',
    tags: ['AWS', 'Kubernetes', 'CI/CD', 'Docker', 'Terraform'],
    function: 'Engineering',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'US overlap',
    aiRelevance: false,
    link: 'https://jobs.lever.co/bluelightconsulting/964a7411-48be-4f7d-a636-fbcf398ae222',
    source: 'Lever',
    sourceDate: '2026-02-07',
    score: 4,
    why: 'DevOps is consistently one of the highest-demand remote roles for LatAm. Bluelight has a strong pipeline of US clients needing infrastructure engineers — stable work, good exposure.',
    whyEs: 'DevOps es consistentemente uno de los roles remotos de mayor demanda para LatAm. Bluelight tiene un flujo constante de clientes en EE.UU. que necesitan ingenieros de infraestructura.',
    applyAngle: 'Lead with your CI/CD pipeline builds, Kubernetes cluster management, and IaC (Terraform/Pulumi). Show uptime ownership and incident response experience.',
    applyAngleEs: 'Lidera con tus pipelines de CI/CD, gestión de clusters de Kubernetes e IaC. Muestra ownership de uptime y experiencia en respuesta a incidentes.',
  },
  {
    id: 'j012',
    company: 'Bluelight Consulting',
    title: 'Ruby on Rails Engineer',
    location: 'Remote · LatAm',
    type: 'Full-time',
    salary: 'Competitive USD',
    salaryEstimate: '$55K–$83K USD',
    salarySource: 'nortec-estimate',
    tags: ['Ruby on Rails', 'PostgreSQL', 'REST APIs', 'SaaS'],
    function: 'Engineering',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'US overlap',
    aiRelevance: false,
    link: 'https://jobs.lever.co/bluelightconsulting/952a0a92-c144-4fbf-9fe8-93f70d8faff3',
    source: 'Lever',
    sourceDate: '2026-01-10',
    score: 3,
    why: 'Rails engineers are underrepresented in LatAm remote hiring which creates real opportunity. Bluelight has consistent client demand for Rails work and explicitly hires across LatAm.',
    whyEs: 'Los ingenieros de Rails están subrepresentados en la contratación remota en LatAm, lo que crea una oportunidad real. Bluelight tiene demanda constante de clientes para trabajo con Rails.',
    applyAngle: 'Show your Rails API design experience, ActiveRecord proficiency, and any SaaS product work. Background in fintech or B2B tools is a strong bonus here.',
    applyAngleEs: 'Muestra tu experiencia en diseño de APIs con Rails, dominio de ActiveRecord y cualquier trabajo en productos SaaS. Experiencia en fintech o herramientas B2B es un plus.',
  },
  {
    id: 'j013',
    company: 'Bluelight Consulting',
    title: 'Fullstack Engineer — Python & React',
    location: 'Remote · LatAm',
    type: 'Full-time',
    salary: 'Competitive USD',
    salaryEstimate: '$65K–$95K USD',
    salarySource: 'nortec-estimate',
    tags: ['Python', 'React', 'PostgreSQL', 'SaaS', 'Fullstack'],
    function: 'Engineering',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'US overlap',
    aiRelevance: false,
    link: 'https://jobs.lever.co/bluelightconsulting/033f2758-81f0-4a1f-96b1-72298824afdc',
    source: 'Lever',
    sourceDate: '2026-04-21',
    score: 4,
    why: 'Python + React is the most in-demand fullstack combination for LatAm remote roles right now. Bluelight provides variety across multiple client projects — good for engineers who want to keep learning.',
    whyEs: 'Python + React es la combinación fullstack más demandada para roles remotos en LatAm ahora mismo. Bluelight ofrece variedad en múltiples proyectos — ideal para ingenieros que quieren seguir aprendiendo.',
    applyAngle: 'Show both sides cleanly — Python backend (APIs, OOP, tests) and React frontend (components, state management, UX thinking). B2B SaaS or fintech experience stands out.',
    applyAngleEs: 'Muestra ambos lados claramente — backend en Python (APIs, OOP, tests) y frontend en React (componentes, estado, pensamiento UX). Experiencia en SaaS B2B o fintech destaca.',
  },
  {
    id: 'j014',
    company: 'Clara',
    title: 'Travel Pay Solutions & Operations Engineer',
    location: 'Remote · LatAm / Americas',
    type: 'Full-time',
    salary: 'Competitive USD',
    salaryEstimate: '$70K–$95K USD',
    salarySource: 'nortec-estimate',
    tags: ['Fintech', 'Payments', 'Solutions Engineering', 'Operations'],
    function: 'Engineering',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'Americas',
    aiRelevance: true,
    link: 'https://job-boards.greenhouse.io/clara/jobs/5095340007',
    source: 'Greenhouse',
    sourceDate: '2026-05-01',
    score: 4,
    why: 'Clara is LatAm\'s leading B2B fintech for spend management — backed by Goldman Sachs and Coatue. This is a technical operations role at the intersection of payments, AI tooling, and client onboarding. Not pure engineering but requires deep technical fluency.',
    whyEs: 'Clara es el fintech B2B líder en LatAm para gestión de gastos — respaldado por Goldman Sachs y Coatue. Este es un rol técnico-operativo en la intersección de pagos, herramientas de IA y onboarding de clientes.',
    applyAngle: 'Highlight structured onboarding experience, fintech or payments domain knowledge, and comfort with complex multi-stakeholder coordination. AI tool fluency (automation, workflow building) is a differentiator.',
    applyAngleEs: 'Destaca experiencia en onboarding estructurado, conocimiento del dominio fintech o pagos, y comodidad coordinando múltiples partes. Fluencia con herramientas de IA es un diferenciador.',
  },
  {
    id: 'j015',
    company: 'CoPilot AI',
    title: 'Customer Success Manager',
    location: 'Remote · LatAm',
    type: 'Full-time',
    salary: '$35,000 USD/yr',
    salaryEstimate: '$35,000 USD/yr',
    salarySource: 'listed',
    tags: ['Customer Success', 'AI', 'Sales', 'Account Management'],
    function: 'Customer Success',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'US overlap',
    aiRelevance: true,
    link: 'https://dynamitejobs.com/location/remote-jobs-in-latinamerica',
    source: 'Dynamite Jobs',
    sourceDate: '2026-05-07',
    score: 4,
    why: 'CoPilot AI is an AI-powered sales prospecting tool — working CS here means deep exposure to AI workflows and sales automation. Salary is listed and honest. Good entry point into the AI SaaS world.',
    whyEs: 'CoPilot AI es una herramienta de prospección de ventas impulsada por IA. Trabajar en CS aquí significa exposición profunda a flujos de trabajo de IA y automatización de ventas. El salario está publicado y es honesto.',
    applyAngle: 'Show prospecting or outbound sales support experience, relationship management, and comfort with AI tools. This company sells to salespeople — knowing that world is a real advantage.',
    applyAngleEs: 'Muestra experiencia en prospección o soporte de ventas outbound, gestión de relaciones y comodidad con herramientas de IA. Esta empresa vende a vendedores — conocer ese mundo es una ventaja real.',
  },
];

export const SALARY_DATA = [
  { role: 'AI Engineer', mid: 118, currency: 'USD K/yr' },
  { role: 'Senior Backend Eng.', mid: 104, currency: 'USD K/yr' },
  { role: 'Frontend Engineer', mid: 94, currency: 'USD K/yr' },
  { role: 'Product Manager', mid: 90, currency: 'USD K/yr' },
  { role: 'Product Designer', mid: 82, currency: 'USD K/yr' },
  { role: 'Customer Success', mid: 65, currency: 'USD K/yr' },
];

export const COMPANIES_HIRING = [
  { name: 'Codeless', category: 'AI/Content', role: 'Senior AI Engineer', salary: '$90K–$130K', tags: ['AI/ML', 'Python', 'LLMs'], flag: '🌎' },
  { name: 'Leaflink', category: 'SaaS', role: 'Customer Success Manager', salary: '$60K–$85K', tags: ['CS', 'SaaS', 'Spanish'], flag: '🌎' },
  { name: 'Linear', category: 'Dev Tools', role: 'Frontend Engineer', salary: '$70K–$110K', tags: ['React', 'TypeScript', 'Web'], flag: '🌎' },
  { name: 'Supabase', category: 'Dev Tools', role: 'Product Designer', salary: '$65K–$95K', tags: ['Design', 'Figma', 'UX'], flag: '🌎' },
];

export function getJobsByFunction(fn) {
  return JOBS.filter(j => j.function === fn);
}

export function getTopJobs(n = 3) {
  return [...JOBS].sort((a,b) => b.score - a.score).slice(0, n);
}
