/* nortec/js/jobs.js — job data with Nortec scoring */

export const JOBS = [
  {
    id: 'j001',
    company: 'Praxent',
    title: 'Senior Software Engineer (React & Node.js)',
    location: 'Remote · LatAm',
    type: 'Full-time',
    salary: 'USD Competitive',
    salaryEstimate: '$75K–$95K USD',
    salarySource: 'nortec-estimate',
    salaryNum: null,
    tags: ['React', 'Node.js', 'Agile', 'REST APIs'],
    function: 'Engineering',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'US CT/ET overlap',
    aiRelevance: false,
    link: 'https://job-boards.greenhouse.io/praxent/jobs/7589205003',
    source: 'Greenhouse',
    sourceDate: '2026-05-09',
    score: 4,
    scoreBreakdown: {
      latamEligibility: 5,
      salaryTransparency: 2,
      remoteQuality: 5,
      careerUpside: 4,
      aiRelevance: 2,
      applicationClarity: 4,
    },
    why: 'Strong fullstack role open explicitly to LatAm. Agile environment, mentorship path, and direct client exposure. Salary not listed but company is well-known for fair USD rates.',
    whyEs: 'Rol fullstack sólido abierto explícitamente para LatAm. Entorno ágil, ruta de mentoría y exposición directa con clientes. No publican salario, pero la empresa es conocida por manejar tarifas justas en USD.',
    applyAngle: 'Highlight sprint delivery experience, fullstack breadth (UI + APIs + cloud), and direct client communication.',
    applyAngleEs: 'Destaca tu experiencia entregando sprints, amplitud fullstack (UI + APIs + nube) y comunicación directa con clientes.',
  },
  {
    id: 'j002',
    company: 'Luxury Presence',
    title: 'Staff Software Engineer — Data Platform & AI',
    location: 'Remote · LatAm',
    type: 'Full-time',
    salary: 'Senior USD',
    salaryEstimate: '$130K–$160K USD',
    salarySource: 'nortec-estimate',
    salaryNum: null,
    tags: ['Python', 'AWS', 'LLMs', 'Data Pipelines', 'PostgreSQL'],
    function: 'Engineering',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'Flexible',
    aiRelevance: true,
    link: 'https://jobs.lever.co/luxurypresence/88e79420-0e50-413b-85c1-58ded03087cd',
    source: 'Lever',
    sourceDate: '2026-03-29',
    score: 5,
    scoreBreakdown: {
      latamEligibility: 5,
      salaryTransparency: 3,
      remoteQuality: 5,
      careerUpside: 5,
      aiRelevance: 5,
      applicationClarity: 5,
    },
    why: 'Sits at the intersection of backend engineering, data infra, and applied AI. MLS data pipelines + LLM agents. Staff-level = career-defining for LatAm engineers.',
    whyEs: 'Está en la intersección de backend, infraestructura de datos e IA aplicada. Pipelines de datos MLS + agentes con LLM. Nivel Staff = una oportunidad que puede definir la carrera de ingenieros en LatAm.',
    applyAngle: 'Show production AI/ML experience (not just prompt engineering), data pipeline work at scale, and observability.',
    applyAngleEs: 'Muestra experiencia real de IA/ML en producción (no solo prompt engineering), trabajo con pipelines de datos a escala y observabilidad.',
  },
  {
    id: 'j003',
    company: 'Clara',
    title: 'Forward-Deployed AI Engineer',
    location: 'Remote · LatAm / São Paulo',
    type: 'Full-time',
    salary: 'USD Competitive',
    salaryEstimate: '$90K–$120K USD',
    salarySource: 'nortec-estimate',
    salaryNum: null,
    tags: ['LLMs', 'Anthropic API', 'Docker', 'PostgreSQL', 'AWS'],
    function: 'Engineering',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'Americas',
    aiRelevance: true,
    link: 'https://job-boards.greenhouse.io/clara/jobs/5095342007',
    source: 'Greenhouse',
    sourceDate: '2026-04-01',
    score: 5,
    scoreBreakdown: {
      latamEligibility: 5,
      salaryTransparency: 3,
      remoteQuality: 5,
      careerUpside: 5,
      aiRelevance: 5,
      applicationClarity: 5,
    },
    why: 'Clara is LatAm-born fintech (backed by Coatue, General Catalyst, Goldman). AI innovation team, ultra-fast shipping culture. Perfect for engineers with 2+ AI features in prod.',
    whyEs: 'Clara es una fintech nacida en LatAm (respaldada por Coatue, General Catalyst y Goldman). Equipo de innovación en IA con cultura de envío ultrarrápido. Ideal para ingenieros con 2+ funcionalidades de IA en producción.',
    applyAngle: 'Show real LLM integrations you shipped to production. Clara wants builders, not AI theorists.',
    applyAngleEs: 'Muestra integraciones reales de LLM que hayas llevado a producción. Clara busca builders, no teóricos de IA.',
  },
  {
    id: 'j004',
    company: 'Rapptr Labs',
    title: 'QA Analyst — iOS & Android Mobile',
    location: 'Remote · LatAm (ET hours)',
    type: 'Full-time',
    salary: 'Disclosed on application',
    salaryEstimate: '$35K–$50K USD',
    salarySource: 'nortec-estimate',
    salaryNum: null,
    tags: ['iOS', 'Android', 'Manual Testing', 'Agile', 'ET overlap'],
    function: 'QA',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'ET (10am–3pm EST core)',
    aiRelevance: false,
    link: 'https://www.glassdoor.com/Job/remote-qa-latam-jobs-SRCH_IL.0,6_IS11047_KO7,15.htm',
    source: 'Glassdoor',
    sourceDate: '2026-05-01',
    score: 3,
    scoreBreakdown: {
      latamEligibility: 5,
      salaryTransparency: 1,
      remoteQuality: 4,
      careerUpside: 3,
      aiRelevance: 1,
      applicationClarity: 4,
    },
    why: 'Solid entry/mid QA role, good for LatAm with ET morning overlap. No salary listed — ask early in the process.',
    whyEs: 'Rol QA sólido de nivel entry/mid, bueno para LatAm con solape en la mañana ET. No publican salario — pregúntalo temprano en el proceso.',
    applyAngle: 'Emphasize detailed test case writing, bug reproduction clarity, and cross-platform mobile experience.',
    applyAngleEs: 'Enfatiza redacción detallada de casos de prueba, claridad al reproducir bugs y experiencia mobile multiplataforma.',
  },
  {
    id: 'j005',
    company: 'Whippy',
    title: 'Customer Success Manager',
    location: 'Remote · LatAm',
    type: 'Full-time',
    salary: '~$35,000 USD/yr',
    salaryEstimate: '$32K–$38K USD',
    salarySource: 'listed',
    salaryNum: 35000,
    tags: ['Customer Success', 'AI Comms', 'English required', 'SaaS'],
    function: 'Customer Success',
    latamEligible: true,
    englishRequired: true,
    tzOverlap: 'US overlap',
    aiRelevance: true,
    link: 'https://www.ziprecruiter.com/Jobs/Remote-Latam-Developer',
    source: 'ZipRecruiter',
    sourceDate: '2026-05-06',
    score: 4,
    scoreBreakdown: {
      latamEligibility: 5,
      salaryTransparency: 5,
      remoteQuality: 5,
      careerUpside: 3,
      aiRelevance: 3,
      applicationClarity: 4,
    },
    why: 'Salary listed — rare and honest. Fast-growing AI comms platform. CS role at an AI company = exposure to AI-native product workflows.',
    whyEs: 'Salario publicado — raro y transparente. Plataforma de comunicación con IA en rápido crecimiento. Un rol de CS en una empresa de IA te da exposición a flujos de producto nativos en IA.',
    applyAngle: 'Show onboarding experience, retention metrics you\'ve influenced, and comfort with async US client communication.',
    applyAngleEs: 'Muestra experiencia en onboarding, métricas de retención que hayas impactado y comodidad con comunicación asíncrona con clientes de EE.UU.',
  },
];

export const SALARY_DATA = [
  { role: 'AI Engineer', mid: 118, currency: 'USD K/yr' },
  { role: 'Senior Backend Eng.', mid: 104, currency: 'USD K/yr' },
  { role: 'Frontend Engineer', mid: 94, currency: 'USD K/yr' },
  { role: 'Product Manager', mid: 90, currency: 'USD K/yr' },
  { role: 'Product Designer', mid: 82, currency: 'USD K/yr' },
  { role: 'Customer Success', mid: 65, currency: 'USD K/yr' },
];

export const COMPANIES_HIRING = [
  { name: 'Codeless', category: 'AI/Content', role: 'Senior AI Engineer', salary: '$90K–$130K', tags: ['AI/ML', 'Python', 'LLMs'], flag: '🌎' },
  { name: 'Leaflink', category: 'SaaS', role: 'Customer Success Manager', salary: '$60K–$85K', tags: ['CS', 'SaaS', 'Spanish'], flag: '🌎' },
  { name: 'Linear', category: 'Dev Tools', role: 'Frontend Engineer', salary: '$70K–$110K', tags: ['React', 'TypeScript', 'Web'], flag: '🌎' },
  { name: 'Supabase', category: 'Dev Tools', role: 'Product Designer', salary: '$65K–$95K', tags: ['Design', 'Figma', 'UX'], flag: '🌎' },
];

export function getJobsByFunction(fn) {
  return JOBS.filter(j => j.function === fn);
}

export function getTopJobs(n = 3) {
  return [...JOBS].sort((a,b) => b.score - a.score).slice(0, n);
}
